---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  annotations:
    gitHubOrg: anees-mscs-org
    gitHubRepo: app16
  name: app16
spec:
  id: app16
  compositionSelector:
    matchLabels:
      type: backend-db-aws
      location: local
  parameters:
    namespace: development
    image: docker.io/syedanees85/app16:latest
    port: 8080
    host: app16.54.211.11.133.nip.io
    db:
      version: "13"
      size: medium
